### ISSUE TITLE
Discovery of existing object will overwrite some elements.

### ISSUE THREAD

**Issue by ekrichbaum** [netboxlabs/diode-agent#10]
Device xyz-sw1, discover from yaml.

Interface type of existing device QFX28 (100GE) changes to Other. This seems to happen on each run.  Fix the interface type, rediscover, and the type will change back to Other.
Rack, position / face delete (but not seemingly in subsequent runs).

Potentially, some extra debug levels would show information on these cases.

**Comment by leoparente** [comment]
hey @ekrichbaum, thanks for you finding. It was a issue on agent side that was passing it `hardcoded` to diode-server. But keep in mind that if the Interface type does not exist in Netbox type list It will be added as `other`

**Comment by leoparente** [comment]
hey @ekrichbaum, thanks for you finding. It is a issue on agent side that is passing the type hardcoded to diode-server and we will fix it.
