### ISSUE TITLE
Document which NetBox object types are discovered by the NAPALM agent

### ISSUE THREAD

**Issue by mrmrcoleman** [netboxlabs/diode-agent#9]
It's currently necessary to look in https://github.com/netboxlabs/diode-agent/blob/develop/diode-napalm-agent/diode_napalm/translate.py to see which NetBox object types would be discovered by the agent.

It would be more convenient to have this documented in the README over here: https://github.com/netboxlabs/diode-agent/blob/develop/diode-napalm-agent/README.md

Possibly here on the main docs too: https://docs.netboxlabs.com/netbox-extensions/diode-agent/

**Comment by leoparente** [comment]
Added in https://github.com/netboxlabs/diode-agent/pull/11
